services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca_juegos_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=bibliotecaJuegos
    networks:
      - biblioteca_network

  db:
    image: mysql:8.0
    container_name: biblioteca_juegos_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bibliotecaJuegos
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - biblioteca_db_data:/var/lib/mysql
      - ./src/config/sentenciaBBDD.sql:/docker-entrypoint-initdb.d/sentenciaBBDD.sql
    networks:
      - biblioteca_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: biblioteca_juegos_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - biblioteca_network

volumes:
  biblioteca_db_data:

networks:
  biblioteca_network:
    driver: bridge